<?php

// vim: ts=4:sw=4:expandtab:

// Defines PHP include path on parent dir
$ip = get_include_path() . ':..';
set_include_path($ip);

error_reporting(E_ALL & E_NOTICE & E_STRICT);

// Setup the autoloading of composer managed libraries
require_once 'vendor/autoload.php';

// 'use' brings that objects in scope and allows IDEs support
// in method discovery and completion on such objects
use \Psr\Http\Message\ServerRequestInterface;
use \Psr\Http\Message\ResponseInterface;
use \Propel\Runtime\Propel;

// Library functions
require_once 'src/lib.php';

// Propel setup using autogenerated config
require_once 'generated-conf/config.php';

// Slim Framework Setup
require_once 'conf/slim.php';
$app = setupSlim();

// Date timezone setup
date_default_timezone_set('UTC');

// Enable errors on assert failure
// assert_options(ASSERT_BAIL, 1);

// === API Routes ===

$app->get('/info',
    function (ServerRequestInterface $request, ResponseInterface $response) {
    $this->logger->info('This is a test message in the Slim logger');

    $logger = Propel::getServiceContainer()->getLogger();
    $logger->notice('This is a test message in the Propel logger');

    $data = [
        'specification-version' => '1.4.0',
        'implementation-version' => '0.9.3',
        'message' => 'sb api'
    ];

    return Web::setupResponseHeaders($response)
            ->write(json_encode($data));
});

require_once 'src/route/profili.php';

require_once 'src/route/postazioni.php';
require_once 'src/route/postazioni_assegnamenti.php';
require_once 'src/route/postazioni_assegnamenti_disponibilita.php';
require_once 'src/route/postazioni_assegnamenti_disponibilita_subaffitti.php';
require_once 'src/route/postazioni_assegnamenti_servizi.php';

require_once 'src/route/clienti.php';
require_once 'src/route/clienti_pagamenti.php';
require_once 'src/route/clienti_postazioni.php';
require_once 'src/route/clienti_schede.php';

require_once 'src/route/abbonamenti.php';
require_once 'src/route/operatori.php';

require_once 'src/route/tipo_servizi.php';
require_once 'src/route/tipo_servizi_costi.php';

$app->run();
